config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  root :to => 'welcome#index'
  resources :file_types
  resources :diagnoses
  resources :reports
  get "terminology" => "terminology#index"
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :genome_references
  resources :assemblies do
    get 'ensure_files_up_to_date'
    get 'ped_info', :on => :collection
    get 'retrieve_circos'
    get 'retrieve_circos_legend'
  end

  get "assembly_files/ped_info", :to => "assembly_files#ped_info", :as => "ped_info"
  resources :assembly_files do
    get 'ped_info', :on => :collection
  end

  resources :assays do
    get 'summary_report', :on => :collection
    get 'ped_info', :on => :collection
  end
  resources :sample_assays
  resources :samples do
    get 'get_drop_down_samples_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'ingenuity_upload', :on => :collection
    post 'ingenuity_missing_samples',:on => :collection
  end
  resources :sample_types
  resources :acquisitions
  resources :people do
    get 'get_drop_down_people_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'receiving_report', :on => :collection
    get 'upload', :on => :collection
    post 'upload_and_validate', :on => :collection
    post 'confirm', :on => :collection
  end
  resources :person_aliases
  resources :traits
  resources :phenotypes
  resources :conditions
  resources :relationships
  resources :aliases
  resources :memberships
  resources :pedigrees do
    get 'pedigree_file'
    post 'pedigree_file'
    get 'all_pedigrees', :on => :collection
    post 'all_pedigree_files', :on => :collection
    get 'pedigree_datastore', :on => :collection
    get 'export_madeline_table'
    get 'export_madeline_pdf', :on => :collection
    get 'export_all_madeline_tables', :on => :collection
    get 'founders'
    get 'founders', :on => :collection
    get 'kwanzaa', :on => :collection
    get 'ped_info', :on => :collection
  end

  resources :studies

  get "/fgg_manifest", :to => "static#fgg_manifest"

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Report.model_name
      end
    end
    super
  end

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  before_destroy :trigger_person_sample_check

  has_many :sample_assays, :dependent => :destroy
  has_many :assays, :through => :sample_assays, :dependent => :destroy
  belongs_to :sample_type
  has_one :acquisition, :dependent => :destroy
  has_one :person, :through => :acquisition

  auto_strip_attributes :sample_vendor_id, :customer_sample_id, :volume, :concentration, :quantity, :protocol, :comments
  validates_presence_of :sample_type_id, :status, :sample_vendor_id #, :volume, :concentration, :quantity
  validates_uniqueness_of :sample_vendor_id, :customer_sample_id

  after_save :check_isb_sample_id, :trigger_person_sample_check
  after_commit :trigger_person_sample_check


  scope :has_pedigree, lambda { |pedigree|
    unless pedigree.blank?
      if pedigree.kind_of?(Array) then
        pedigree_id = pedigree[0]
      elsif pedigree.kind_of?(ActionController::Parameters) or pedigree.kind_of?(Hash) then
        pedigree_id = pedigree[:id]
      else
        pedigree_id = pedigree.to_i
      end
      logger.debug("pedigree_id #{pedigree_id}")
      unless pedigree_id.blank?
        joins(person: :pedigree)
          .where(pedigrees: {id: pedigree_id})
      end
    end
  }

  scope :has_person, lambda { |person|
    unless person.blank? or person[:id].nil?
      person_id = person[:id]
      unless person_id.blank?
        joins(:person).where('people.id = ?', person_id)
      end
    end
  }

  scope :order_by_pedigree, -> { includes(person: :pedigree).order('pedigrees.name') }

  def check_isb_sample_id
    if self.isb_sample_id.nil? or !self.isb_sample_id.match(/isb_sample/) then
      isb_sample_id = "isb_sample_"+self.id.to_s
      self.isb_sample_id = isb_sample_id
      self.save
    end
  end

  def trigger_person_sample_check
    person = self.person
    return if person.nil?
    person.check_sequencing_status
  end

  def varfile
    self.assays.each do |assay|
      assay.assemblies.each do |assembly|
        if assembly.assembly_files.where(:file_type_id => 1).count > 0 then
	        return true
	      end
      end
    end
    return false
  end

  def identifier
    if self.person.nil? then
      return "#{isb_sample_id} - #{sample_vendor_id} - NA"
    else
      return "#{isb_sample_id} - #{sample_vendor_id} - #{self.person.identifier}"
    end
  end

  def pedigree
    begin
      return self.person.pedigree
    rescue
      logger.error("Error with pedigree_id call for sample #{self.inspect}")
      return nil
    end
  end

end

app/models/sample_type.rb
class SampleType < ActiveRecord::Base
  has_many :samples

  auto_strip_attributes :name, :description, :tissue
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/samples_controller.rb
require 'will_paginate/array'
require 'ingenuity'
require 'download_zip'

class SamplesController < ApplicationController
  unloadable
  respond_to :json
  cache_sweeper :sample_sweeper

  # GET /samples
  # GET /samples.xml
  def index
    #@samples = Sample.has_pedigree(params[:pedigree_filter]).find(:all, :include => [:assays, {:person => :pedigree }], :order => ['pedigrees.name'])
    if params[:name] or params[:sample_vendor_id] then
      nameArg=params[:name] if params[:name]
      nameArg=params[:sample_vendor_id] if  params[:sample_vendor_id]
      if nameArg.match(/%/) then
        @samples = Sample.where("sample_vendor_id like ?", nameArg)
          .includes(person: {pedigree: :study })
          .order('samples.sample_vendor_id').paginate :page => params[:page], :per_page => 100
      else
        @samples = Sample.where("sample_vendor_id = ?", nameArg)
          .includes(person: { pedigree: :study})
          .order('samples.sample_vendor_id').paginate :page => params[:page], :per_page => 100
      end
    elsif params[:customer_sample_id] then
      nameArg=params[:customer_sample_id] if  params[:customer_sample_id]
      if nameArg.match(/%/) then
        @samples = Sample.where("customer_sample_id like ?", nameArg)
          .includes(person: { pedigree: :study },
                :order => ['samples.customer_sample_id']).paginate :page => params[:page], :per_page => 100
      else
        @samples = Sample.where("customer_sample_id = ?", nameArg)
        .includes(person: { pedigree: :study})
        .order('samples.customer_sample_id').paginate :page => params[:page], :per_page => 100
      end
    elsif params[:customer_subject_id] then
        # aka person.collaborator_id
        nameArg=params[:customer_subject_id] if  params[:customer_subject_id]
        if nameArg.match(/%/) then
            @samples = Sample.includes(person: { pedigree: :study})
                        .where('people.collaborator_id like ?', nameArg)
                        .order('samples.sample_vendor_id').paginate :page => params[:page], :per_page => 100
        else
            @samples = Sample.includes(person: { pedigree: :study})
                        .where(people: {collaborator_id: nameArg})
                        .order('samples.sample_vendor_id').paginate :page => params[:page], :per_page => 100
        end
    elsif params[:id] then
      if params[:id].match(/%/) then
        @samples = Sample.where("samples.id like ?", params[:id])
        .includes(person: { pedigree: :study})
        .order('samples.id').paginate :page => params[:page], :per_page => 100
      else
        idNum=params[:id].gsub(/isb_sam.*_/,"")
        @samples = Sample.where("id = ?", idNum)
        .includes(person: { pedigree: :study})
        .order('samples.id').paginate :page => params[:page], :per_page => 100
      end
    elsif params[:person] then
      logger.debug("in samples by person #{params[:person]}")
      @samples = Sample.includes(person: :pedigree).has_person(params[:person])
        .order('pedigrees.name').paginate :page => params[:page], :per_page => 100
    elsif params[:problems] then
      #@samples = Sample.where( Acquisition.where( Acquisition.arel_table[:sample_id].eq(Sample.arel_table[:id]) ).exists.not ).paginate(:page => params[:page], :per_page => 10)
      @samples = Sample.where.not(id: Acquisition.pluck(:sample_id)).paginate(:page => params[:page], :per_page => 10)
    else

      respond_to do |format|
        format.html {
          @samples = Sample.has_pedigree(params[:pedigree_filter])
            .order('samples.id')
            .paginate :page => params[:page], :per_page => 100
        }
        format.any  {
          @samples = Sample.has_pedigree(params[:pedigree_filter])
            .order('samples.id')
        }
      end

    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @samples }
      format.json { respond_with @samples }
      format.js
    end
  end

  # GET /samples/1
  # GET /samples/1.xml
  def show
    @sample = Sample.includes(:assays, { person: :pedigree}).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sample }
      format.json { render :json => @sample.to_json(:include => :assays) }
    end
  end

  # GET /samples/new
  # GET /samples/new.xml
  def new
    @sample = Sample.new
    @pedigrees = Pedigree.order(:tag)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.includes(:assays, {person: :pedigree}).find(params[:id])
    @pedigrees = Pedigree.order(:tag)
  end

  # POST /samples
  # POST /samples.xml
  def create
    @sample = Sample.new(sample_params)
    logger.debug("creating a new sample #{@sample.inspect}")
    if params[:check_dates] then
      if params[:check_dates][:add_date_submitted].to_i != 1 then
        @sample.date_submitted = nil
      end
    end

    if params[:sample_type] then
      @sample.sample_type_id = params[:sample_type][:id]
    end

    if params[:status] then
      @sample.status = params[:status]
    end

    # need to make usre thatperson[id] is not null
    begin
      person = Person.find(params[:person][:id])
    rescue
      @sample.errors.add(:person, 'must be selected')
      render :action => "new" and return
    end
    @sample.person = person

    respond_to do |format|
      if @sample.save
         #check acquisition
	 acq_check = Acquisition.find_by_person_id_and_sample_id(params[:person][:id], @sample.id)
	 if acq_check.nil? then
           #create acquisition
           acquisition = Acquisition.new
           acquisition.person_id = params[:person][:id]
           acquisition.sample_id = @sample.id
           acquisition.save
         end
        format.html { redirect_to(@sample, :notice => 'Sample was successfully created.') }
        format.xml  { render :xml => @sample, :status => :created, :location => @sample }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.xml
  def update
    @sample = Sample.find(params[:id])
    @pedigrees = Pedigree.order("pedigrees.tag")

    ac_notice = ''
    if (params[:person] and params[:person][:id]) then
      if (@sample.person.nil? || params[:person][:id].to_i != @sample.person.id.to_i) then
        #logger.debug("updating the person associated with this sample from #{@sample.person.id} to #{params[:person][:id]}")
	#check that there isn't an entry for this acquisition in the db already!
	check_aq = Acquisition.where(person_id: params[:person][:id], sample_id: @sample.id)
	if (check_aq.size > 0) then
	  @sample.errors.add("Cannot create duplicate sample (#{@sample.id}) and person (#{@sample.person.id}) link.")
	else
	  if (@sample.person) then
    	    acquisition = Acquisition.where(person_id: @sample.person.id, sample_id: @sample.id)
	    if (acquisition.size > 1) then
	      #logger.debug("Found multiple samples for this sample (#{@sample.id}) and person(#{@sample.person.id}) combination!!!  This is an error in the database!!  Fix it manually!  #{acquisition.inspect}")
  	      @sample.errors.add("Found multiple samples for sample #{@sample.id} and person #{@sample.person.id}.  Fix manually.")
	    else
	      acquisition = acquisition.first
	      acquisition.person_id = params[:person][:id]
	      if (acquisition.save) then
	        ac_notice << "Sample association with Person was successfully updated."
	      else
	        ac_notice << "Sample association update failed."
	        @sample.errors.add(ac_notice)
	      end
	    end
	  else
	    # create a new acquisition
	    acquisition = Acquisition.new(person_id: params[:person][:id], sample_id: @sample.id)
	    if (acquisition.save) then
	      ac_notice << "Created new association between sample and person."
	    else
	      ac_notice << "Failed to create a new association between sample and person."
	    end
	  end
        end
      end

      # check to see if sequenced is true on person.  if not, then update it to yes.
      person = Person.find(params[:person][:id])
      if (person.sequenced? == false) then
  	person.planning_on_sequencing = 1
	if (person.save) then
          ac_notice << "  Updated person to show that sequencing was done."
        end
      end
    end
    @sample.errors.add(:sample, ac_notice) unless ac_notice.empty?

    respond_to do |format|
      if @sample.update_attributes(sample_params)
        #logger.debug("sample is #{@sample.inspect} after params #{sample_params}")
        format.html { redirect_to(@sample, :notice => "Sample was successfully updated. #{ac_notice}") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit", :notice => "Sample failed updating .#{ac_notice}" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.xml
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to(samples_url) }
      format.xml  { head :ok }
    end
  end

  def get_drop_down_samples_by_pedigree
    # returns sample id : person full_identifier
    samples = Sample.includes(:person, :pedigree, :person_aliases).where(pedigree_id: params[:pedigree_id])
    options = samples.collect { |x| "\"#{x.id}\" : \"#{x.person.full_identifier}\""}
    render :text => "{#{options.join(",")}}"
  end

  def ped_info
    ped_info = Hash.new
    Sample.all.each do |s|
      ped = s.pedigree
      next if ped.nil?
      ped_info[s.sample_vendor_id] = ped.isb_pedigree_id
      ped_info[s.isb_sample_id] = ped.isb_pedigree_id
    end

    respond_to do |format|
      format.html
      format.xml {head :ok}

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_with model: @sample do |f| %>
  <%= render "partials/error_messages", :target => @sample %>
  <%= render "partials/pedigree_person_select", :pedigrees => @pedigrees, :f => f %>

  <div class="field">
    <%= f.label :customer_sample_id %> - The Sample ID if it is different than Subject ID.<br/>
    <%= f.text_field :customer_sample_id %>
  </div>
  <div class="field">
    <%= f.label :sample_type_id %><br />
    <%= collection_select(:sample_type, :id, SampleType.all, :id, :name, {:prompt => "Select a Type for this sample", :selected => @sample.sample_type_id || ''}) %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.collection_select(:status, ["Pending", "Submitted", "Sequenced", "Failed QC"], :titleize, :titleize, { :include_blank => "-Select Sample Status", :selected => @sample.status || '' }) %>
  </div>
  <div class="field">
    Vendor Sample ID (ex: GS0001-DNA_A01 or SS6002729) <br />
    <%= f.text_field :sample_vendor_id %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :concentration %><br />
    <%= f.text_field :concentration%>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :date_submitted %><br />
    <%= f.date_select :date_submitted %>
    <%= check_box("check_dates", "add_date_submitted") %>
    Update date submitted?
  </div>
  <div class="field">
    <%= f.label :protocol %><br />
    <%= f.text_field :protocol %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/_list.html.erb
<% if @samples.size > 0 %>
<table class="tablesorter">
  <thead>
  <tr>
    <th class="{sorter: 'digit'}">Name</th>
    <th>ISB ID</th>
    <th>Customer Sample ID</th>
    <th>Person&nbsp;&nbsp;&nbsp;</th>
    <th>Pedigree&nbsp;&nbsp;&nbsp;</th>
    <th>Sample&nbsp; type&nbsp;</th>
    <th>Status&nbsp;&nbsp;&nbsp;</th>
    <th>Volume&nbsp;&nbsp;&nbsp;</th>
    <th>Concentration&nbsp;&nbsp;&nbsp;</th>
    <th>Quantity&nbsp;&nbsp;&nbsp;</th>
    <th colspan="3" class="nosort">Controls&nbsp;&nbsp;&nbsp;</th>
  </tr>
  </thead>
  <tbody>
<% @samples.each do |sample| %>
  <tr>
    <td><%= link_to sample.sample_vendor_id,sample if sample.sample_vendor_id %></td>
    <td><%= link_to sample.isb_sample_id, sample, :id => sample.id %></td>
    <td><%= sample.customer_sample_id %></td>
    <% if sample.person.nil? then %>
    <td colspan="3">No person information.  Add <%= link_to('a link', :controller => "acquisitions", :action => "new", :sample_id => sample.id) %> </td>
    <% else %>
    <% if sample.person.collaborator_id.nil? then %>
    <td colspan="1"><%= link_to sample.person.isb_perons_id, sample.person  %>
    <%else%>
    <td colspan="1"><%= link_to sample.person.collaborator_id, sample.person  %>
    <%end%>
    <td><%= link_to(sample.person.pedigree.name, sample.person.pedigree.name )if sample.person.pedigree %></td>
    <% end %>
    <td><%= sample.sample_type.nil? ? 'unknown' : sample.sample_type.name  %></td>
    <td><%= sample.status %></td>
    <td><%= sample.volume %></td>
    <td style="width:150"><%= sample.concentration %></td>
    <td><%= sample.quantity %></td>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
      <% if false  %><td><%= link_to 'Delete sample', sample, :confirm => 'Are you sure?', :method => :delete %></td><% end %>

  </tr>
<% end %>
</tbody>
</table>

<%= will_paginate @samples %>
<% else %>
<table class="tablesorter">
  <tr><td>No samples found for this query</td></tr>
</table>
<% end %>

app/views/samples/_search.html.erb
<%= form_tag("#", :method => "get") do %>
  Search for a Sample Vendor ID: <%= text_field_tag("sample_vendor_id") %>
  <%= submit_tag("Search") %>
<% end %>
<%= form_tag("#", :method => "get") do %>
    Search for a Customer Sample ID: <%= text_field_tag("customer_sample_id") %>
    <%= submit_tag("Search") %>
<% end %>
<%= form_tag("#", :method => "get") do %>
    Search for a Customer Subject ID: <%= text_field_tag("customer_subject_id") %>
    <%= submit_tag("Search") %>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<script>
  $(document).ready(function() { $(".tablesorter").tablesorter({
    "theme": "blue",
    textExtraction: function(node) {
        if (node.innerHTML.indexOf("isb_sample_") != -1){
	  var id = node.childNodes[0].id;
	  return id;
	} else if (node.innerHTML.indexOf("isb_ind_") != -1) {
	  var id = node.innerHTML.replace("isb_ind_","");
	  return id;
	}
	return node.innerHTML;
      }
    });
  });
</script>
<h1>Listing samples</h1>
<%= render "partials/filter" %> OR
<%= render "search" %>
<%= link_to 'New Sample', new_sample_path %>

<div id="filter_table">
  <%= render 'list' %>
</div>
<br />

app/views/samples/index.js.erb
$("#filter_table").replaceWith("<div id=\"filter_table\"><%= escape_javascript(render 'list') %></div>");
$(".tablesorter").tablesorter({widgets: ['zebra']});

app/views/samples/ingenuity_upload.html.erb
<h1>Choose upload file</h1>
<p>Uploads and parses a list of samples uploaded to ingenuity then outputs a list of samples that have yet to be uploaded to Ingenuity</p>
<% if flash[:error] then %>
<div id="error_explanation"><%= flash[:error].html_safe %></div>
<% end %>
<%=form_tag('/samples/ingenuity_missing_samples', :multipart => true) %>
<div class="field">
  <%= label "sample", :file %><br />
  <%= file_field_tag "file" %>
</div>
<%= submit_tag "Process this file" %>
</form>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<td id="notice"><%= notice %></p>

<h1>Sample Information</h1>
<table class="tablesorter">
  <tr>
  <td>
    <b>ISB sample:</b>
    <%= @sample.isb_sample_id %>
 </td>
 <td >
   <b>Vendor ID:</b>
   <%= @sample.sample_vendor_id %>
 </td>
 <td colspan="2">
   <b>Customer ID:</b>
   <%= @sample.customer_sample_id %>
 </td>
 </tr>
 <tr>
 <% if @sample.person.nil? then %>
 <td>&nbsp</td>
 <span style="font-weight: bold; color: red;">No person information for this sample</span>
 <% else %>
  <td >
      <b>Person:</b>
      <% if @sample.person.collaborator_id.nil? then %>
      <%= link_to @sample.person.isb_person_id, @sample.person  %>
      <%else%>
      <%= link_to @sample.person.collaborator_id, @sample.person  %>
      (<%= link_to @sample.person.isb_person_id, @sample.person  %>)
<%end%>
<td>
  <b>Pedigree:</b>
  <%= link_to @sample.person.pedigree.name, pedigree_path(@sample.person.pedigree) %>
</td>
<td >
  <b>Status:</b>
  <% rr = Hash.new; rr[:pedigree_filter] = Hash.new; rr[:pedigree_filter][:id] = @sample.person.pedigree.id %>
  <%= link_to @sample.status, receiving_report_people_path(rr) %>
</td>
<% end %>
<td>
  <b>Date submitted:</b>
  <%= @sample.date_submitted %>
</td>
</tr>
<tr>
<td>
  <b>Sample type:</b>
  <%= @sample.sample_type.nil? ? 'unknown' : @sample.sample_type.name %>
</td>
  <td>
    <b>Volume:</b>
    <%= @sample.volume %>
  </td>
  <td>
    <b>Concentration:</b>
    <%= @sample.concentration %>
  </td>
  <td>
    <b>Quantity:</b>
    <%= @sample.quantity %>
  </td>
</tr>
<tr>
<td colspan="4">
  <b>Protocol:</b>
  <%= @sample.protocol %>
</td>
</tr>
<tr>
<td colspan="4">
  <b>Comments:</b>
  <%= @sample.comments %>
</td>
</tr>
</table>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Delete this sample', @sample, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back to all samples', samples_path %> |
<% if !@sample.person.nil? %>
<%= link_to("Back to Person #{@sample.person.identifier}", person_path(@sample.person)) %> |
<%= link_to( "Back to Pedigree #{@sample.person.pedigree.name}", pedigree_path(@sample.person.pedigree.id) )%>
<% end %>
<h1>Listing assays</h1>
<% if @sample.assays.size > 0 %>
<table class="tablesorter">
  <thead>
  <tr>
    <th>Name</th>
    <th>ID</th>
    <th>Sample</th>
    <th>Customer Sample ID</th>
    <th>ISB Sample ID</th>
    <th>ISB Person ID&nbsp;&nbsp;&nbsp;</th>
    <th>Collaborator ID&nbsp;&nbsp;&nbsp;</th>
    <th>Pedigree</th>
    <th>Assay type</th>
    <th>Technology&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @sample.assays.each do |assay| %>
  <tr>
    <td><%= link_to assay.name, assay %></td>
    <td><%= link_to "isb_asy_"+assay.id.to_s, assay %></td>
    <td><%= assay.sample.sample_vendor_id %></td>
    <td><%= assay.sample.customer_sample_id %></td>
    <td><%= assay.sample.isb_sample_id %></td>
    <% if assay.sample.person.nil? then %>
    <td colspan="3">No Person information for this sample</td>
    <% else %>
    <td><%= assay.sample.person.isb_person_id %></td>
    <td><%= assay.sample.person.collaborator_id %></td>
    <td><%= assay.sample.person.pedigree.name %></td>
    <% end %>
    <td><%= assay.assay_type %></td>
    <td><%= assay.technology %></td>
    <td><%= assay.status %></td>
  </tr>
<% end %>
</tbody>
</table>
<% else %>
<p>No assays for this sample</p>
<% end %>
<%= link_to 'Add new assay', new_assay_path(:sample_id => @sample) %>

<br/>

<h1>Listing assemblies</h1>
<% if @sample.assays.size > 0 %>
<table class="tablesorter">
  <thead>
  <tr>
    <th>Name</th>
    <th>ID</th>
    <th>Assay</th>
    <th>Sample</th>
    <th>Customer Sample</th>
    <th>Genome reference&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Assembler version</th>
    <th>Date Recieved</th>
    <th>Current</th>
  </tr>
  </thead>
  <tbody>
  <% @sample.assays.each do |assay| %>
  <% assay.assemblies.each do |assembly| %>
  <tr>
    <td><%= link_to assembly.name, assembly %></td>
    <td><%= link_to "isb_asm_"+assembly.id.to_s, assembly %></td>
    <td><%= link_to assay.name, assay %></td>
    <td><%= assay.sample.sample_vendor_id %></td>
    <td><%= assay.sample.customer_sample_id %></td>
    <td><%= assembly.genome_reference.name %></td>
    <td><%= assembly.software_version %> </td>
    <td><%= assembly.file_date %> </td>
    <td><%= assembly.current %> </td>
  </tr>
<% end %>
<% end %>
</tbody>
</table>
<% else %>
<p>No assemblies for this sample</p>
<% end %>
<%= link_to 'Add new assembly', new_assembly_path(:sample_id => @sample) %>
<script>
  $(document).ready(function() { $(".tablesorter").tablesorter({"theme": "blue"}); });
</script>