config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  root :to => 'welcome#index'
  resources :file_types
  resources :diagnoses
  resources :reports
  get "terminology" => "terminology#index"
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :genome_references
  resources :assemblies do
    get 'ensure_files_up_to_date'
    get 'ped_info', :on => :collection
    get 'retrieve_circos'
    get 'retrieve_circos_legend'
  end

  get "assembly_files/ped_info", :to => "assembly_files#ped_info", :as => "ped_info"
  resources :assembly_files do
    get 'ped_info', :on => :collection
  end

  resources :assays do
    get 'summary_report', :on => :collection
    get 'ped_info', :on => :collection
  end
  resources :sample_assays
  resources :samples do
    get 'get_drop_down_samples_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'ingenuity_upload', :on => :collection
    post 'ingenuity_missing_samples',:on => :collection
  end
  resources :sample_types
  resources :acquisitions
  resources :people do
    get 'get_drop_down_people_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'receiving_report', :on => :collection
    get 'upload', :on => :collection
    post 'upload_and_validate', :on => :collection
    post 'confirm', :on => :collection
  end
  resources :person_aliases
  resources :traits
  resources :phenotypes
  resources :conditions
  resources :relationships
  resources :aliases
  resources :memberships
  resources :pedigrees do
    get 'pedigree_file'
    post 'pedigree_file'
    get 'all_pedigrees', :on => :collection
    post 'all_pedigree_files', :on => :collection
    get 'pedigree_datastore', :on => :collection
    get 'export_madeline_table'
    get 'export_madeline_pdf', :on => :collection
    get 'export_all_madeline_tables', :on => :collection
    get 'founders'
    get 'founders', :on => :collection
    get 'kwanzaa', :on => :collection
    get 'ped_info', :on => :collection
  end

  resources :studies

  get "/fgg_manifest", :to => "static#fgg_manifest"

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Report.model_name
      end
    end
    super
  end

end

app/models/pedigree.rb
require 'pedigree_info'
require 'madeline_utils'

class Pedigree < ActiveRecord::Base
  after_save :check_pedigree_tag, :check_isb_pedigree_id
  after_update :check_pedigree_tag, :check_isb_pedigree_id
  before_destroy :destroy_people

  has_many :memberships, :dependent => :destroy
  has_many :people, :through => :memberships, :dependent => :destroy
  belongs_to :study

  auto_strip_attributes :name, :tag, :description
  validates_presence_of :name, :tag, :study_id
  validates_uniqueness_of :name, :tag


  def phenotypes
    self.people.map(&:phenotypes).flatten.uniq
  end

  def conditions
    self.people.map(&:conditions).flatten.uniq
  end

  def write_pedigrees
    data_store = pedigree_info
    json_data_store = ActiveSupport::JSON.encode(data_store)
    File.open("isb-pedigrees.dat", 'w') do |f|
      f.puts json_data_store
    end
  end

  # count the child and spouse relationships
  def relationship_count
    count = 0
    self.people.each do |person|
      count += person.offspring.size
      count += person.spouses.size
    end
    return count
  end

  def find_childless_marriages
    ordered_people = ordered_pedigree(self.id)
    cm = Array.new
    cmhash = Hash.new
    ordered_people.each do |person|
      next if person.nil?
      #logger.debug("find_childless_marriages person #{person.inspect}")
      #logger.debug("preson spouses #{person.spouses}")
      #logger.debug("prson offspring #{person.offspring}")
      if (person.spouses.size > 0 and person.offspring.empty?) then
        #logger.debug("person is a candidate! #{person.spouses.size} #{person.offspring.empty?}")
        unless (cm.include?(person.id)) then
          #logger.debug("adding person to cm!")
          cm.push(person.id)
          cm.push(person.spouses.first.relation.id)
          cmhash[person.id] = person.spouses.first.relation.id
        end
      end
    end
    #logger.debug("find_childless_marriages #{cmhash.inspect}")
    return cmhash
  end

  def check_pedigree_tag
    if self.tag and self.tag.match(/ /) then
      tag = self.tag.gsub!(/ /, "_")
      self.tag = tag
      self.save
    end
  end

  def check_isb_pedigree_id
    if self.isb_pedigree_id.nil? then
      isb_ped = 'isb_ped_'+self.id.to_s
      self.isb_pedigree_id = isb_ped
      self.save
    end
  end

  def children
	children = Array.new
	self.people.each do |person|
		person.relationships.each do |rel|
			if rel.name == "child" then
				children.push(person)
			end
		end
	end
	children.uniq!
  end

  def trios
	Rails.cache.fetch("trios/#{id}", :expires_in => 7.days) do
		trios = self.nTuple(3)
	end
  end

  def quartets
	Rails.cache.fetch("quartets/#{id}", :expires_in => 7.days) do
		quartets = self.nTuple(4)
	end
  end

  # returns COMPLETE families - therefore skips anything that doesn't have a mother and a father
  def nTuple(family_size)
	raise "nTuple family_size must be at least 3" unless family_size >= 3
	child_size = family_size -2
    tuple = Array.new
    peopleByFamily = Hash.new
    self.people.each do |person|
      (father_rel, mother_rel) = person.parents
       next if father_rel.nil? or mother_rel.nil?
       father = father_rel.relation # person is the child
       mother = mother_rel.relation
       peopleByFamily[father] = Hash.new if peopleByFamily[father].nil?
       peopleByFamily[father][mother] = Array.new if peopleByFamily[father][mother].nil?
       peopleByFamily[father][mother].push(person)
    end
    peopleByFamily.each do |father, inner|
      inner.each do |mother, children|
        childrenCombos = children.combination(child_size).to_a
		next if childrenCombos.empty?
		tuple.push([father, mother, childrenCombos])
      end
    end

    return tuple
  end

  def genomic_count
    complete_count = 0
    self.people.each do |person|
        if person.complete then
            complete_count = complete_count+1
        end
    end
    return complete_count
  end

  # return 1 if there are no 'planning_on_sequencing' members that don't have assembly files
  def complete
    plan_count = 0
    complete_count = 0
    self.people.each do |person|
      if person.planning_on_sequencing then
        # check to see if they have a sample. return true if one sample is complete
	    plan_count = plan_count+1
        if person.complete then
	        complete_count = complete_count+1
	    end
      end
    end
    return true if ((plan_count > 0) and (plan_count == complete_count))
    return false
  end

  def count_sequenced
	Rails.cache.fetch("count_sequenced/#{id}", :expires_in => 7.days) do
		numSequenced = 0
		self.people.each do |person|
			numSequenced+=1 if person.complete
		end
		numSequenced
	end
  end

  def destroy_people
    people = self.people
    #logger.debug("found #{people.inspect} in destroy_people")
    people.each do |person|
      person.destroy
    end

  end

end

app/controllers/pedigrees_controller.rb
require 'download_zip'
require 'madeline_utils'
require 'pedigree_info'
require 'utils'
require 'csv'

class PedigreesController < ApplicationController
  unloadable
  respond_to :json
  caches_page :all_pedigrees
  cache_sweeper :pedigree_sweeper

  # GET /pedigrees
  # GET /pedigrees.xml
  def index
    @pedigrees = Pedigree.includes(:study, :people).order('studies.name', 'pedigrees.name')
    if params[:name] or  params[:pedigree_name] then
      @pedigrees = Pedigree.includes(:study, :people).where(:name => [params[:name] , params[:pedigree_name]] ).paginate :page => params[:page], :per_page => 100
    elsif params[:id]
      @pedigrees = Pedigree.includes(:study, :people).where("pedigrees.id = ? or pedigrees.isb_pedigree_id = ?",
                                  params[:id],params[:id]).paginate :page => params[:page], :per_page => 100
    else
      respond_to do |format|
        format.html {
          @pedigrees = Pedigree.includes(:study, :people).order('studies.name', 'pedigrees.name')
        }
        format.any{
          @pedigrees = Pedigree.includes(:study, :people).order('pedigrees.id')
        }
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pedigrees }
      format.json { respond_with @pedigrees }
    end
  end

  # GET /pedigrees/1
  # GET /pedigrees/1.xml
  def show
    @pedigree = Pedigree.find(params[:id])
    people_ids = @pedigree.people.map(&:id)

    @person_relationships = Relationship.display_filter.order(:person_id, :relation_order)
      .where("person_id in (?)", @pedigree.people.map(&:id))

#    @person_relationships = Relationship.order(:person_id).find_all_by_person_id(@pedigree.people.map(&:id))
#    @relation_relationships = Relationship.find_all_by_relation_id(@pedigree.people.map(&:id))
#    @relationships = @person_relationships + @relation_relationships

    unless @pedigree.tag.match(/unrelateds/) or @pedigree.tag == 'diversity_P1' or @pedigree.people.size <= 2 or @pedigree.relationship_count < 2 then
      madeline_file = madeline_image(@pedigree)
      if File.exists?(madeline_file) then
        @madeline = File.read(madeline_file)
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pedigree }
      format.json  { respond_with @pedigree }
    end
  end

  # GET /pedigrees/new
  # GET /pedigrees/new.xml
  def new
    @pedigree = Pedigree.new
    if (params[:study])
      @pedigree.study_id = params[:study]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pedigree }
    end
  end

  # GET /pedigrees/1/edit
  def edit
    @pedigree = Pedigree.find(params[:id])
    @studies = Study.all
  end

  # POST /pedigrees
  # POST /pedigrees.xml
  def create
    @pedigree = Pedigree.new(pedigree_params)

    @pedigree.version = 1
    respond_to do |format|
      if @pedigree.save then
        format.html { redirect_to(@pedigree, :notice => 'Pedigree was successfully created.') }
        format.xml  { render :xml => @pedigree, :status => :created, :location => @pedigree }
        format.json  { render :json => @pedigree, :status => :created, :location => @pedigree }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pedigree.errors, :status => :unprocessable_entity }
        format.json  { render :json => @pedigree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pedigrees/1
  # PUT /pedigrees/1.xml
  def update
    @pedigree = Pedigree.find(params[:id])

    respond_to do |format|
      if @pedigree.update_attributes(pedigree_params)
        format.html { redirect_to(@pedigree, :notice => 'Pedigree was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pedigree.errors, :status => :unprocessable_entity }
        format.json  { render :json => @pedigree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pedigrees/1
  # DELETE /pedigrees/1.xml
  def destroy
    @pedigree = Pedigree.find(params[:id])
    @pedigree.destroy

    respond_to do |format|
      format.html { redirect_to(pedigrees_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end

  # this prints out the JSON pedigree file
  def pedigree_file
    @pedigree = Pedigree.find(params[:pedigree_id])
    peddir_exists
    output_file = PEDFILES_DIR + pedigree_output_filename(@pedigree)
    ped_hash = pedfile(params[:pedigree_id])
    parent_rels = pedigree_relationships(params[:pedigree_id])
    ped_hash["relationships"] = parent_rels
    json_pedigree = JSON.pretty_generate(ped_hash)
    File.open(output_file, 'w') do |f|
      f.puts json_pedigree
    end

    respond_to do |format|
      format.html { send_data(File.read(output_file), :filename => "#{@pedigree.tag}.ped", :type => 'application/json') }
      format.json { send_data(File.read(output_file), :filename => pedigree_output_filename(@pedigree), :type => 'application/json') }
    end
  end

  def all_pedigree_files
    peddir_exists
    @pedigrees = Pedigree.all
    ped_file_list = Hash.new
    @pedigrees.each do |ped|
      file_name = pedigree_output_filename(ped)
      output_file = PEDFILES_DIR + file_name
      ped_file_list[file_name] = output_file
      ped_hash = pedfile(ped.id)
      parent_rels = pedigree_relationships(ped.id)
      ped_hash["relationships"] = parent_rels
      json_pedigree = JSON.pretty_generate(ped_hash)
      File.open(output_file, 'w') do |f|
        f.puts json_pedigree
      end
    end

    respond_to do |format|
      format.html {
        # add the data_store to the zip file
        data_store = pedindex('FILE','TAG')
        data_store_name = PEDIGREE_DATA_STORE # from config/environment.rb
        data_store_loc = PEDFILES_DIR + data_store_name
        ped_file_list[data_store_name] = data_store_loc
        json_index = JSON.pretty_generate(data_store)
        File.open(data_store_loc, 'w') do |f|
          f.puts json_index
        end

        download_zip("pedigrees.zip",ped_file_list)
      }
      format.json {
        contents = Array.new
	ped_file_list.each do |file, file_loc|
	  contents.push(File.read(file_loc))
	end
	send_data(contents.join(","), :filename => "all_peds", :type => 'application/json')
      }
    end

  end

  def all_pedigrees
    @ped_list = Hash.new
    Pedigree.all.each do |ped|
      ped_info =pedfile(ped.id)
      rels = pedigree_relationships(ped.id)
      ped_info["relationships"] = rels
      json_ped = JSON.pretty_generate(ped_info)
      @ped_list[ped.id] = json_ped
    end

    respond_to do |format|
    	format.html
	format.json {
		render :json => @ped_list
	}
    end
  end



  def pedigree_datastore
    peddir_exists

    if params[:type] and params[:type].match('REST') then
      data_store = pedindex('REST','ID')
    else
      data_store = pedindex('FILE','TAG')
    end

    json_index = JSON.pretty_generate(data_store)
    respond_to do |format|
      format.html {
        send_data(json_index, :filename => "index", :type => "applicaton/json")
      }
      format.json {
        send_data(json_index, :filename => "index", :type => "applicaton/json")
      }
    end
  end

  def madeline_image(pedigree)
      peddir_exists
      maddir_exists
      # the combination of pedigree name and pedigree id should be unique
      madeline_name = madeline_file(pedigree)
      madeline_file = MADELINE_DIR + "#{madeline_name}"

      ordered_ped = ordered_pedigree(pedigree.id)
      madeline_array = to_madeline(pedigree,ordered_ped)
      @filename = madeline_file

      labels = Array.new
      labels.push("IndividualID")
      labels << pedigree.conditions.map{|d| d.name.gsub!(/ /, '_')}
      #labels << pedigree.phenotypes.map{|p| p.name.gsub!(/ /,'_')}
      labels << pedigree.people.map { |p| p.phenotypes.where(:madeline_display => 1)}.flatten.uniq.map{|l| l.name.gsub!(/ /,'_')}
	    logger.debug("madeline_image labels are #{labels.inspect}")
      madeline_info = Array.new
      madeline_array.each do |line|
        line = line.join("\t")
        madeline_info.push(line)
      end

      infile = Tempfile.new('madeline_input')
      header = madeline_header(pedigree)
      infile.print(header)
      infile.print("\n")
      infile.print(madeline_info.join("\n"))
      infile.flush
      infile.close
      FileUtils.copy(infile.path, "/tmp/blah.txt")

      madeline_table = array_to_html_table(header.split(/\t/), madeline_array)
      madeline_table.gsub!(/table/, "table border=\"1\" cellspacing=\"0\"") #dunno how to get XMLBuilder to return a border
      # we want to regenerate the file every time because something may have changed.
      begin
        tmpfile, warnings = Madeline::Interface.new(:embedded => true, :L => labels, "font-size"=> "10", "nolabeltruncation" => true, "sort" => "SortOrder").draw(File.open(infile,'r'))
      rescue Exception => e
        msg = e.message.gsub(/\e\[(\d+)m/, '')
        msg.gsub!(/\n/, '<br />')
        msg.gsub!(/[^0-9A-Za-z \/<>-]/, '')
        msg.gsub!(/131m/,'')
        flash[:error] = "#{msg}"
      else
        FileUtils.copy(tmpfile,madeline_file)
      end

      return madeline_file
  end

  def export_madeline_table
    @pedigree = Pedigree.find(params[:pedigree_id])
    ordered_ped = ordered_pedigree(@pedigree.id)
    madeline_array = to_madeline(@pedigree,ordered_ped)
    header = madeline_header(@pedigree).split(/\t/)

    csvdir_exists
    csv_file_name = "#{CSVDIR}/#{@pedigree.tag}_madeline_table_#{Date.today.to_s}.csv"
    CSV.open(csv_file_name, "wb") do |csv|
      csv << header
      madeline_array.each do |row|
        csv << row
      end
    end

    respond_to do |format|

app/helpers/pedigrees_helper.rb
module PedigreesHelper
end

app/views/pedigrees/_form.html.erb
<%= form_with model: @pedigree do |f| %>
  <%= render "partials/error_messages", :target => @pedigree %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :study %><br />
    <%= collection_select(:pedigree, :study_id, Study.order(:name), :id, :name, options = {:prompt => '-Select a study for this pedigree'}, :selected => params[:study_id], :class => "study_select") %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedigrees/edit.html.erb
<h1>Editing pedigree</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedigree %> |
<%= link_to 'Back', pedigrees_path %>

app/views/pedigrees/founders.html.erb
<% if params[:id] then %>
  <% cur_pedigree_id = params[:id] %>
<% elsif params[:pedigree_filter] && params[:pedigree_filter][:id] and !params[:pedigree_filter][:id].blank? then %>
  <% cur_pedigree_id = params[:pedigree_filter][:id].to_i %>
<% else %>
  <% cur_pedigree_id = nil %>
<% end %>
<h1>Founders<% if cur_pedigree_id then %> for pedigree <%= Pedigree.find(cur_pedigree_id).name %><% end %></h1>

<% if @founders.size == 0 %>
  <p>No founders found</p>
<% else %>
<%= @founders.count %> founders <br /><br />
<%= form_tag("#", :method => "get") do %>
  <%= collection_select(:pedigree_filter, :id, Pedigree.order(:name), :id, :name, options = {:include_blank => '-Select a pedigree to filter by', :selected => cur_pedigree_id}, :class => "pedigree_select") %>
<%= submit_tag("Filter") %>
<% end %>

<table class="tablesorter">
  <thead>
  <tr>
    <th>ISB Person ID</th>
    <th>Collaborator ID</th>
    <th>Pedigree</th>
  </tr>
  </thead>
  <tbody>
<% @founders.each do |id, person| %>
  <tr>
    <td style="width: 100px;"><%= link_to person.isb_person_id, person %></td>
    <td><%= link_to person.full_collaborator, person_path(person) %></td>
    <td><%= link_to person.pedigree.name, pedigree_path(person.pedigree) if person.pedigree %></td>
  </tr>
<% end %>
</tbody>
</table>
<% end %>

<br />
<br />

app/views/pedigrees/index.html.erb
<?xml version="1.0" encoding="utf-8"?>
<script>
  $(document).ready(function() { $(".tablesorter").tablesorter({"theme": "blue"}); });
</script>

<h1>Listing pedigrees</h1>
<%= link_to 'New Pedigree', new_pedigree_path %>
<%= link_to 'Upload a list of people into a Pedigree', upload_people_path %>
<%= button_to "Download All Pedigree Files and Index", all_pedigree_files_pedigrees_path %>

<table id="pedigrees" class="tablesorter">
  <thead>
  <tr>
    <th>Status&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Name</th>
    <th>ID</th>
    <th>Tag&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Study</th>
    <th>Description</th>
    <th>Num People</th>
    <th>Controls</th>
  </tr>
  </thead>
  <tbody>
  <% @pedigrees.each do |pedigree| %>
    <tr>
      <% if pedigree.complete then %>
        <td style="background-color:green"><span style="color: green;">C</span></td>
      <% else %>
        <td style="background-color:red"><span style="color: red;">I</span></td>
      <% end %>
      <td><%= link_to pedigree.name, pedigree %></td>
      <td><%= link_to pedigree.isb_pedigree_id, pedigree %></td>
      <td><%= link_to pedigree.tag,pedigree %></td>
      <td><%= link_to pedigree.study.name, pedigree.study if pedigree.study %></td>
      <td style="white-space: normal;"><%= pedigree.description %></td>
      <td><%= pedigree.people.count %></td>
      <td><%= link_to 'Edit', edit_pedigree_path(pedigree) %></td>
      <% if false  %><td><%= link_to 'Delete pedigree', pedigree, :confirm => 'Are you sure?', :method => :delete %></td><% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br />


app/views/pedigrees/new.html.erb
<h1>New pedigree</h1>

<%= render 'form' %>

<%= link_to 'Back', pedigrees_path %>

app/views/pedigrees/show.html.erb
<script>
  $(document).ready(function() {
    $(".tablesorter").tablesorter({widgets: ['zebra'], theme: "blue"});
  });
</script>

<p id="notice"><%= notice %></p>
<% if flash[:error] then %>
<p id="error_explanation"><%= flash[:error].html_safe %></p>
<% end %>
<h1>Pedigree <%= @pedigree.name %></h1>


<table class="tablesorter">
<tr>
<td>
  <b>Name:</b>
  <%= @pedigree.name %>
</td>
<td>
  <b>ID:</b>
  <%= @pedigree.isb_pedigree_id %>
</td>

<td>
  <b>Tag:</b>
  <%= @pedigree.tag %>
</td>
<td>
  <b>Study:</b>
  <%= link_to @pedigree.study.name,@pedigree.study if @pedigree.study %>
</td>
</tr>
<tr>

<td colspan="4">
  <b>Description:</b>
  <%= @pedigree.description %>
</td>
</tr>
<tr><td colspan="4"><b>Pedigree Status:</b> <% if @pedigree.complete then %><span style="background-color:green;">&nbsp;&nbsp;</span>Complete<% else %><span style="background-color:red;">&nbsp;&nbsp;</span>Incomplete<% end %></td></tr>
</table>
<%= link_to 'Back', pedigrees_path %> |
<%= link_to 'Edit', edit_pedigree_path(@pedigree) %> |
<% par = Hash.new;  par[:pedigree_filter] = Hash.new;  par[:pedigree_filter][:id] = @pedigree.id %>
<%= link_to "Receiving Log for Pedigree #{@pedigree.name}", receiving_report_people_path(par) %> |
<% if false %> <%= link_to "Delete pedigree #{@pedigree.name}, all people, and all samples associated", @pedigree, :confirm => "Are you sure you want to delete this pedigree, all of its people, and all of their associated information (including samples)?", :method => :delete %> <% end %>
<br />
<br />
<%= button_to "Download Pedigree File", pedigree_pedigree_file_path(@pedigree) %>
<p><span style="font-weight: bold; text-decoration: underline;">People in this Pedigree</span></p>
<% if @pedigree.people.size == 0 %>
  <p>No people currently entered for this pedigree</p>
<% else %>
  <table class="tablesorter" id="PedigreePeople">
    <thead>
    <tr>
      <th>Person</th>
      <th>Subject</th>
      <th>Gender</th>
      <th>Dob</th>
      <th>Dod</th>
      <th>Number of Samples</th>
      <th>Sample Vendor ID</th>
      <th>Customer Sample ID</th>
      <th>Number of Phenotypes</th>
      <th>Number of Conditions Diagnosed</th>
    </tr>
    </thead>
    <tbody>
    <% ordered_pedigree(@pedigree.id).each do |person| %>
      <% if person.nil? %>
        <tr><td colspan="8">People in this pedigree have been incorrectly linked to other pedigrees via incorrect relationships.  Please check the database for information about this pedigree and fix it.</td></tr>
      <% else %>
      <tr>
        <td><% if person.planning_on_sequencing %><span style="background-color:<% if person.complete then %>green<% else %>red<% end %>">&nbsp;&nbsp;</span><% else %>&nbsp;&nbsp;<% end %> <%= link_to person.isb_person_id, person %></td>
        <td><%= person.full_collaborator %></td>
        <td><%= person.gender %></td>
        <td><%= person.dob %></td>
        <td><%= person.dod %></td>
	<% if person.samples.count > 0 %>
	  <td><%= link_to person.samples.count, samples_path(:person => {:id => person}) unless person.samples.nil? %></td>
	  <% if person.samples.count == 1 %>
	    <td><%= person.samples.first.sample_vendor_id %></td>
	    <% if person.samples.first.customer_sample_id.nil? %>
	      <td>NA</td>
	    <% else %>
	      <td><%= person.samples.first.customer_sample_id %></td>
	    <% end %>
	  <% else %>
      <td><%= image_tag('file_location.png', :size => "20x20", :title => person.samples.map(&:sample_vendor_id).join(", "),
            data: { toggle: "tooltip", placement: "right", trigger: 'click hover focus'},
            :id => "person_#{person.id}") %>
            <%= link_to 'Multiple Samples', samples_path(:person => {:id => person}) %>
      </td>
      <td><%= image_tag('file_location.png', :size => "20x20",
          :title => person.samples.map(&:customer_sample_id).collect! {|obj| obj.nil? ? 'NA' : obj }.join(", "),
          data: { toggle: "tooltip", placement: "right", trigger: 'click hover focus'},
          :id => "person_customer_#{person.id}") %>
      <%= link_to 'Multiple Samples', samples_path(:person => {:id => person}) %></td>
	  <% end %>
	<% else %>
	  <td>NA</td>
	  <td>NA</td>
	  <td>NA</td>
	<% end %>
	<td><%= person.phenotypes.count > 0 ? link_to(person.phenotypes.count, traits_path(:person => person)) : person.phenotypes.count  %></td>
	<td><%= person.conditions.count > 0 ? link_to(person.conditions.count, person_path(person)) : person.conditions.count %></td>
      </tr>
      <% end %>
    <% end %>
    <tbody>
  </table>
<% end %>
<%= link_to 'Add Person', new_person_path(:pedigree_id => @pedigree) %>
<br /><br />


<% if @pedigree.people.size > 2 %>
  <% unless @pedigree.name.match(/unrelated/) %>
    <%= link_to "Download madeline table", pedigree_export_madeline_table_path(@pedigree) %>
    <% if false %><%= raw @madeline_table %><br /><% end %>

    <%= raw(@madeline) %>
  <% end %>
<% end %>
<br /><br />
<h1>Conditions Diagnosed in this pedigree</h1>
<%= render 'conditions/list', :conditions => @pedigree.conditions.paginate(:per_page => 5) %>
<br /><br />
<h1>Phenotypes in this pedigree</h1>
<%= render 'partials/phenotypes', :phenotypes => @pedigree.phenotypes %>
<br />
<h1>Relationships</h1>
<% if @person_relationships.size > 0 %>
  <table class="tablesorter" id="PedigreePeople">
    <thead>
    <tr>
    <th>Parent</th>
    <th>Name</th>
    <th>Child</th>
    <th>Relation Order</th>
    <th colspan="2" class="nosort">Controls</th>
    </tr>
    </thead>
    <tbody>
<% @person_relationships.each do |relationship| %>
  <% next unless relationship.relation %>
  <tr>
    <td><%= link_to relationship.person.collaborator_id, relationship.person %></td>
    <td>is the <%= link_to relationship.name, relationship %> of </td>
    <td><%= link_to relationship.relation.collaborator_id, relationship.relation %></td>
    <td><%= relationship.relation_order %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
  </tr>
<% end %>
</tbody></table>
<% else %>
  <p>No relationships</p>
<% end %>
<br />
<% par = Hash.new;  par[:pedigree_filter] = Hash.new;  par[:pedigree_filter][:id] = @pedigree.id %>
<%= link_to 'New Relationship', new_relationship_path(par) %>
<br />
<br />
<br />
<br />