config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  root :to => 'welcome#index'
  resources :file_types
  resources :diagnoses
  resources :reports
  get "terminology" => "terminology#index"
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :genome_references
  resources :assemblies do
    get 'ensure_files_up_to_date'
    get 'ped_info', :on => :collection
    get 'retrieve_circos'
    get 'retrieve_circos_legend'
  end

  get "assembly_files/ped_info", :to => "assembly_files#ped_info", :as => "ped_info"
  resources :assembly_files do
    get 'ped_info', :on => :collection
  end

  resources :assays do
    get 'summary_report', :on => :collection
    get 'ped_info', :on => :collection
  end
  resources :sample_assays
  resources :samples do
    get 'get_drop_down_samples_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'ingenuity_upload', :on => :collection
    post 'ingenuity_missing_samples',:on => :collection
  end
  resources :sample_types
  resources :acquisitions
  resources :people do
    get 'get_drop_down_people_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'receiving_report', :on => :collection
    get 'upload', :on => :collection
    post 'upload_and_validate', :on => :collection
    post 'confirm', :on => :collection
  end
  resources :person_aliases
  resources :traits
  resources :phenotypes
  resources :conditions
  resources :relationships
  resources :aliases
  resources :memberships
  resources :pedigrees do
    get 'pedigree_file'
    post 'pedigree_file'
    get 'all_pedigrees', :on => :collection
    post 'all_pedigree_files', :on => :collection
    get 'pedigree_datastore', :on => :collection
    get 'export_madeline_table'
    get 'export_madeline_pdf', :on => :collection
    get 'export_all_madeline_tables', :on => :collection
    get 'founders'
    get 'founders', :on => :collection
    get 'kwanzaa', :on => :collection
    get 'ped_info', :on => :collection
  end

  resources :studies

  get "/fgg_manifest", :to => "static#fgg_manifest"

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Report.model_name
      end
    end
    super
  end

end

app/models/trait.rb
class Trait < ActiveRecord::Base
  belongs_to :person
  belongs_to :phenotype

  auto_strip_attributes :trait_information, :output_order
  validates_presence_of :person_id, :phenotype_id

  scope :has_pedigree, lambda { |pedigree|
    unless pedigree.blank?
      if pedigree.kind_of?(Array) then
        pedigree_id = pedigree[0]
      elsif pedigree.kind_of?(ActionController::Parameters) or pedigree.kind_of?(Hash) then
        pedigree_id = pedigree[:id]
      else
        pedigree_id = pedigree.to_i
      end
      unless pedigree_id.blank?
        joins(:person => :pedigree)
        .where(pedigrees: {id: pedigree_id})
      end
    end
  }

  scope :has_person, lambda { |person_id|
    unless person_id.blank?
      where(:person_id, person_id)
    end
  }

  def get_people_by_phenotype_and_trait_value(phenotype, trait_value)
        people = Array.new
        return people
  end


end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  # GET /traits
  # GET /traits.xml
  def index
    @traits = Trait.has_pedigree(params[:pedigree_filter]).has_person(params[:person]).paginate :page => params[:page], :per_page => 100

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @traits }
      format.js
    end
  end

  # GET /traits/1
  # GET /traits/1.xml
  def show
    @trait = Trait.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trait }
    end
  end

  # GET /traits/new
  # GET /traits/new.xml
  def new
    @trait = Trait.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trait }
    end
  end

  # GET /traits/1/edit
  def edit
    @trait = Trait.find(params[:id])
  end

  # POST /traits
  # POST /traits.xml
  def create
    @trait = Trait.new(trait_params)

    respond_to do |format|
      if @trait.save
        format.html { redirect_to(@trait, :notice => 'Trait was successfully created.') }
        format.xml  { render :xml => @trait, :status => :created, :location => @trait }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trait.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /traits/1
  # PUT /traits/1.xml
  def update
    @trait = Trait.find(params[:id])

    respond_to do |format|
      if @trait.update_attributes(trait_params)
        format.html { redirect_to(@trait, :notice => 'Trait was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trait.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /traits/1
  # DELETE /traits/1.xml
  def destroy
    @trait = Trait.find(params[:id])
    @trait.destroy

    respond_to do |format|
      format.html { redirect_to(traits_url) }
      format.xml  { head :ok }
    end
  end

  private
  def trait_params
    params.require(:trait).permit(:person_id, :phenotype_id, :trait_information, :output_order)
  end
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/traits/_form.html.erb
<%= form_with model: @trait do |f| %>
  <%= render "partials/error_messages", :target => @trait %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.collection_select(:person_id, Person.includes(:pedigree, :person_aliases).order('pedigrees.name', 'collaborator_id'), :id, :full_identifier, { :prompt => "-Select Person", :selected => params[:person_id]}) %>
  </div>
  <div class="field">
    <%= f.label :phenotype_id %><br />
    <%= f.collection_select(:phenotype_id, Phenotype.order(:name), :id, :name, { :prompt => "-Select Phenotype"}) %>
  </div>
  <div>If your phenotype is not here, then <%= link_to "Create a new phenotype", new_phenotype_path %></div>
  <div class="field">
    <%= f.label :trait_information %><span>  (Ex: the value of the trait)</span><br />
    <%= f.text_field :trait_information %>
  </div>
  <div class="field">
    <%= f.label :output_order %><br />
    <%= f.text_field :output_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traits/_list.html.erb
<% if @traits.size > 0 %>
<table class="tablesorter">
  <thead>
  <tr>
    <th>Pedigree</th>
    <th>Person</th>
    <th>Phenotype</th>
    <th>Value</th>
    <th>Output order</th>
    <th class="nosort">controls</th>
  </tr>
  </thead>
  <tbody>
<% @traits.each do |trait| %>
  <tr>
    <td><% if trait.person.pedigree %><%= trait.person.pedigree.name %><% else %>No Pedigree<% end %></td>
    <td><%= trait.person.identifier %></td>
    <td><%= trait.phenotype.name if trait.phenotype %></td>
    <td><%= trait.trait_information %></td>
    <td><%= trait.output_order %></td>
    <td><%= link_to 'Show', trait %></td>
    <% if false %>
    <td><%= link_to 'Edit', edit_trait_path(trait) %></td>
    <td><%= link_to 'Destroy', trait, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>
<%= will_paginate @traits %>

<% else %>
  <table class="tablesorter">
  <% if params[:person] %>
  <p>No traits for person <%if params[:person] %><%= Person.includes(:pedigree, :person_aliases).find(params[:person]).full_identifier %><% end %></p>
  <% else %>
  <p>No traits for person</p>
  <% end %>
  </table>
<% end %>

app/views/traits/edit.html.erb
<h1>Editing trait</h1>

<%= render 'form' %>

<%= link_to 'Show', @trait %> |
<%= link_to 'Back', traits_path %>

app/views/traits/index.html.erb
<script>
  $(document).ready(function() {
    $(".tablesorter").tablesorter({widgets: ['zebra']});
  });
</script>

<h1>Listing traits</h1>
<%= render "partials/filter" %>
<%= link_to 'New Trait', new_trait_path %>
<div id="filter_table">
  <%= render 'list', :traits => @traits %>
</div>

<br />

app/views/traits/index.js.erb
$("#filter_table").replaceWith("<div id=\"filter_table\"><%= escape_javascript(render 'list', :traits => @traits) %></div>")
$(".tablesorter").tablesorter({widgets: ['zebra']});

app/views/traits/new.html.erb
<h1>New trait</h1>

<%= render 'form' %>

<%= link_to 'Back', traits_path %>

app/views/traits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @trait.person.full_identifier %>
</p>

<p>
  <b>Phenotype:</b>
  <%= @trait.phenotype.name %>
</p>

<p>
  <b>Value:</b>
  <%= @trait.trait_information %>
</p>

<p>
  <b>Output order:</b>
  <%= @trait.output_order %>
</p>

<%= link_to 'Add another trait for this person', new_trait_path(:person_id => @trait.person) %> |
<%= link_to 'Edit', edit_trait_path(@trait) %> |
<%= link_to 'Back', traits_path %><br />
<%= link_to 'Back to Person', person_path(@trait.person) %> |
<%= link_to 'Back to Pedigree', pedigree_path(@trait.person.pedigree) %>