config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  root :to => 'welcome#index'
  resources :file_types
  resources :diagnoses
  resources :reports
  get "terminology" => "terminology#index"
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :genome_references
  resources :assemblies do
    get 'ensure_files_up_to_date'
    get 'ped_info', :on => :collection
    get 'retrieve_circos'
    get 'retrieve_circos_legend'
  end

  get "assembly_files/ped_info", :to => "assembly_files#ped_info", :as => "ped_info"
  resources :assembly_files do
    get 'ped_info', :on => :collection
  end

  resources :assays do
    get 'summary_report', :on => :collection
    get 'ped_info', :on => :collection
  end
  resources :sample_assays
  resources :samples do
    get 'get_drop_down_samples_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'ingenuity_upload', :on => :collection
    post 'ingenuity_missing_samples',:on => :collection
  end
  resources :sample_types
  resources :acquisitions
  resources :people do
    get 'get_drop_down_people_by_pedigree', :on => :collection
    get 'ped_info', :on => :collection
    get 'receiving_report', :on => :collection
    get 'upload', :on => :collection
    post 'upload_and_validate', :on => :collection
    post 'confirm', :on => :collection
  end
  resources :person_aliases
  resources :traits
  resources :phenotypes
  resources :conditions
  resources :relationships
  resources :aliases
  resources :memberships
  resources :pedigrees do
    get 'pedigree_file'
    post 'pedigree_file'
    get 'all_pedigrees', :on => :collection
    post 'all_pedigree_files', :on => :collection
    get 'pedigree_datastore', :on => :collection
    get 'export_madeline_table'
    get 'export_madeline_pdf', :on => :collection
    get 'export_all_madeline_tables', :on => :collection
    get 'founders'
    get 'founders', :on => :collection
    get 'kwanzaa', :on => :collection
    get 'ped_info', :on => :collection
  end

  resources :studies

  get "/fgg_manifest", :to => "static#fgg_manifest"

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Report.model_name
      end
    end
    super
  end

end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :pedigrees, :dependent => :destroy
  auto_strip_attributes :name, :tag, :collaborator, :collaborating_institution, :lead, :description, :contact
  validates_presence_of :name, :tag, :collaborator, :collaborating_institution
  validates_uniqueness_of :name, :tag

  after_save :check_study_tag
  after_update :check_study_tag
  after_create :check_study_tag


  def check_study_tag
    if !self.tag.nil? and self.tag.match(/ /) then
      tag = self.tag.gsub!(/ /,"_")
      self.tag = tag
      self.save
    end
  end

  def genomic_count
    total_count = 0
    self.pedigrees.each do |ped|
        ped_count = ped.genomic_count
        total_count = total_count + ped_count
    end
    return total_count
  end

  def count_trios
    Rails.cache.fetch("numTrios/#{id}", :expires_in => 7.days) do
      numTrios = 0
      self.pedigrees.each do |ped|
        numTrios += ped.trios[0][2].count unless ped.trios.empty?
      end
      numTrios
    end
    end

  def count_individuals
	Rails.cache.fetch("numPeople/#{id}",:expires_in => 7.days) do
		numPeople = 0
		self.pedigrees.each do |ped|
			numPeople += ped.people.count
		end
		numPeople
	end
  end

  def count_sequenced
	Rails.cache.fetch("numSequenced/#{id}",:expires_in => 7.days) do
		numPeople =0
		self.pedigrees.each do |ped|
			numPeople += ped.count_sequenced
		end
		numPeople
	end
  end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  # GET /studies
  # GET /studies.xml
  def index
    @studies = Study.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @studies }
    end
  end

  # GET /studies/1
  # GET /studies/1.xml
  def show
    @study = Study.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @study }
    end
  end

  # GET /studies/new
  # GET /studies/new.xml
  def new
    @study = Study.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @study }
    end
  end

  # GET /studies/1/edit
  def edit
    @study = Study.find(params[:id])
  end

  # POST /studies
  # POST /studies.xml
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to(@study, :notice => 'Study was successfully created.') }
        format.xml  { render :xml => @study, :status => :created, :location => @study }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /studies/1
  # PUT /studies/1.xml
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(study_params)
        format.html { redirect_to(@study, :notice => 'Study was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.xml
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      format.html { redirect_to(studies_url) }
      format.xml  { head :ok }
    end
  end

  private
  def study_params
    params.require(:study).permit(:name, :tag, :lead, :collaborator, :collaborating_institution, :description, :contact)
  end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= form_with model: @study do |f| %>
  <%= render "partials/error_messages", :target => @study %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :lead %><br />
    <%= f.text_field :lead %>
  </div>
  <div class="field">
    <%= f.label :collaborator %><br />
    <%= f.text_field :collaborator %>
  </div>
  <div class="field">
    <%= f.label :collaborating_institution %><br />
    <%= f.text_field :collaborating_institution %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<script>
  $(document).ready(function() { $(".tablesorter").tablesorter({"theme": "blue"}); });
</script>
<h1>Listing studies</h1>

<table class="tablesorter">
  <thead>
  <tr>
    <th>Name</th>
    <th>Lead&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Collaborator&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Collaborating Institution&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th width="100">Description&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Contact&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="nosort" colspan="3">Controls</th>
  </tr>
  </thead>
  <tbody>
<% @studies.each do |study| %>
  <tr>
    <td><%= link_to study.name, study %></td>
    <td><%= study.lead %></td>
    <td style="white-space: normal;"><%= study.collaborator %></td>
    <td style="whtie-space: normal;"><%= study.collaborating_institution %></td>
    <td style="white-space: normal;"><%= study.description %></td>
    <td style="white-space: normal;"><%= study.contact %></td>
    <td><%= link_to 'Edit', edit_study_path(study) %></td>
    <% if false %><td><%= link_to 'Destroy', study, :confirm => 'Are you sure?', :method => :delete %></td><% end %>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Study', new_study_path %>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<script>
  $(document).ready(function() {
    $(".tablesorter").tablesorter({widgets: ['zebra']});
  });
</script>
<p id="notice"><%= notice %></p>
<% if flash[:error] then %>
<p id="error_explanation"><%= flash[:error].html_safe %></p>
<% end %>
<table class="tablesorter">
<tr>
<td>
  <b>Name:</b>
  <%= @study.name %>&nbsp;&nbsp;&nbsp;<b>ID:</b><%= 'isb_study_'+@study.id.to_s %>
</td>
<td>
  <b>Tag:</b>
  <%= @study.tag %>
</td>

<td>
  <b>Lead:</b>
  <%= @study.lead %>
</td>
</tr>
<tr>
<td>
  <b>Principle Investigator:</b>
  <%= @study.collaborator %>
</td>

<td>
  <b>Collaborating Institution:</b>
  <%= @study.collaborating_institution %>
</td>
<td>
  <b>Contact:</b>
  <%= @study.contact %>
</td>
</tr>
<tr>
<td colspan="3">
  <b>Description:</b>
  <%= @study.description %>
</td>
</tr>
<tr>
  <td><b>Num Individuals:</b><%= @study.count_individuals %></td>
  <td><b>Num Complete Trios:</b><%= @study.count_trios %></td>
</tr>
</table>

<% if false %> <%= link_to "Delete study #{@study.name}, all pedigrees, all people, and all samples associated", @study, :confirm => "Are you sure you want to delete this study, all of its pedigrees, all of its people, and all of their associated information (including samples)?", :method => :delete %> <% end %>

<p>
  <b>Genome Count:</b>
  <%= @study.genomic_count %>
</p>


<p>
  <b>Pedigrees</b>
<% if not @study.pedigrees %>
  <p>No pedigrees for this study</p>
<% else %>
<b>(<%= @study.pedigrees.count %>)</b>:<br>
<table class="tablesorter">
  <tr>
    <th>Pedigree Name</th>
    <th>Pedigree Tag</th>
    <th>Pedigree Description</th>
    <th style="colspan: 3;">Controls</th>
  </tr>
<% @study.pedigrees.each do |pedigree| %>
  <tr>
    <td><%= link_to pedigree.name, pedigree %></td>
    <td><%= pedigree.tag %></td>
    <td><%= pedigree.description %></td>
    <td><%= link_to 'Edit', edit_pedigree_path(pedigree) %></td>
    <% if false %>
    <td><%= link_to 'Show', pedigree %></td>
    <td><%= link_to 'Destroy', pedigree, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
<% end %>
</p>

<%= link_to "Download Madeline tables for this study", export_all_madeline_tables_pedigrees_path(:study => @study) %>
<br />
<br />
<%= link_to 'Add Pedigree', new_pedigree_path(:study => @study) %>
<br />

<%= link_to 'Edit Study', edit_study_path(@study) %> |
<%= link_to 'Back to Study Index', studies_path %>
<br />
<br />